# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
  error_controller: Labstag\Controller\FrontController::error
  cache:
    pools:
      doctrine.result_cache_pool:
        adapter: cache.app
      doctrine.system_cache_pool:
        adapter: cache.system
  rate_limiter:
    api_requests:
      policy: 'token_bucket'
      limit: 100
      interval: '1 hour'
  trusted_proxies: '%env(TRUSTED_PROXIES)%'
  secret: '%env(APP_SECRET)%'
  csrf_protection: true
  handle_all_throwables: true

  # Note that the session will be started ONLY if you read or write from it.
  session:
    handler_id: null
    cookie_httponly: true
    cookie_secure: auto
    cookie_samesite: strict
    storage_factory_id: session.storage.factory.native
  #esi: true
  #fragments: true

when@test:
  framework:
    test: true
    session:
      storage_factory_id: session.storage.factory.mock_file
